-- Initial database schema for Internship Tracker API.

CREATE TABLE companies
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    website     VARCHAR(255),
    description VARCHAR(2000),
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE vacancies
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT       NOT NULL,
    title       VARCHAR(150) NOT NULL,
    link        VARCHAR(500),
    city        VARCHAR(100),
    work_format VARCHAR(30)  NOT NULL,
    description VARCHAR(2000),
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_vacancies_company
        FOREIGN KEY (company_id)
            REFERENCES companies (id),

    CONSTRAINT vacancies_work_format_check
        CHECK (work_format IN (
            'OFFICE',
            'REMOTE',
            'HYBRID',
            'NOT_SPECIFIED'
            ))
);

CREATE TABLE applications
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id      BIGINT      NOT NULL,
    status          VARCHAR(30) NOT NULL,
    applied_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    next_contact_at TIMESTAMP(6) WITHOUT TIME ZONE,
    notes           VARCHAR(2000),
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT fk_applications_vacancy
        FOREIGN KEY (vacancy_id)
            REFERENCES vacancies (id),

    CONSTRAINT applications_status_check
        CHECK (status IN (
            'PLANNED',
            'APPLIED',
            'TEST_TASK',
            'INTERVIEW',
            'OFFER',
            'REJECTED',
            'WITHDRAWN'
            ))
);
